name: akilli_tahta
description: "Pardus ve Windows uyumlu, sınıf içi etkileşimli eğitim için geliştirilmiş açık kaynaklı PDF ve beyaz tahta uygulaması."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  get_it: ^9.2.1
  google_fonts: ^8.1.0
  path_provider: ^2.1.5
  pdfrx: ^2.2.24
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
